### ISSUE TITLE
include use trait and render it

### ISSUE THREAD

**Issue by tonicospinelli** [tonicospinelli/ClassGeneration#4]
I just wanted to ask if you'd looked at adding the ability to include traits in a class? It seems you currently only have the ability to define that a class is a trait. I also noticed that when compiling the template for a class it only contemplates constants, properties and methods.

The implementation isn't simple, due to the complexity that can exist when traits resolve method conflicts, and how you would easily expose an API to define that and then render it.

I'd be interested in contributing at least a simple version, which allows individual traits to be added, with the option to specify an alias and set visibility.

by @jameswatts

**Comment by tonicospinelli** [comment]
@jameswatts could you take a look my firsts steps about this issue [feature-use-trait](https://github.com/tonicospinelli/ClassGeneration/compare/feature-use-trait?expand=1)?

**Comment by jameswatts** [comment]
Looking good!

The ```alias``` and ```visibility``` override apply to a specific method of the trait, not the trait itself. From the PHP docs:

```php
class MyClass2 {
    use HelloWorld { sayHello as private myPrivateHello; }
}
```

https://github.com/tonicospinelli/ClassGeneration/blob/feature-use-trait/src/ClassGeneration/UseTraitCollection.php#L49

The `UseTraitCollection::toString()` method renders all of the trait declarations on a single line. This is fine, but here is where I could see that a ```{ ... }``` would be redered *if* there are aliases, visibility or conflict resolutions defined, example from the PHP docs:

```php
class Aliased_Talker {
    use A, B {
        B::smallTalk insteadof A; // conflict resolution
        A::bigTalk insteadof B;
        B::bigTalk as talk; // aliasing
    }
}
```

I'm not sure how best to handle defining those. For me, both *aliasing* and *visibility overriding* would be defined for each individual trait. However, *conflict resolution* may be something you would define on the collection, as it applies to the traits it contains. But it feels like a smell leaking the specifics of the traits to the collection. Not sure how that could be done another way though.

**Comment by tonicospinelli** [comment]
Yes, about `alias` and `visibility` I made a mistake, this methods never should exists on it.

I did read more about trait and the classes were renamed from `UseTrait` to `Composition`.

So, I think the next step is to solve conflicts of methods following this way:
* create something like `CompositionMethod` which has `name`, `alias` and `visibility`.
* `Composition` has `CompositionMethodCollection`
* `CompositionMethodCollection` parses to string all `CompositionMethods` imploding one per line
* On `CompositionCollection::toString` wrapping `CompositionMethod` with `{}` if they exist.

this can work :wink:

**Comment by jameswatts** [comment]
OK. Would be good to have some helper methods on the `CompositionCollection`, to easily create those `CompositionMethod` objects internally without having to create them and access the `CompositionMethodCollection`. It could become a lot of code for the end developer otherwise.

Something like this:

```php
$compositionCollection->alias('MyTrait', 'myMethod', 'newMethodName', 'private');
// renders as: "MyTrait::myMethod as private newMethodName;"
```

Note that in the example above it covers the fact that you can do both *aliasing* and *visibility* changes at once. However, you may just want to modify *visibility*, for which there could be a specific method:

```php
$compositionCollection->visibility('MyTrait', 'myMethod', 'protected');
// renders as: "MyTrait::myMethod as protected;"
```

You could also allow for easy *conflict resolution*, like this:

```php
$compositionCollection->resolve('MyTrait', 'myMethod', 'OtherTrait');
// renders as: "MyTrait::myMethod insteadof OtherTrait;"
```

I'm not sure if you'd prefer to access the trait and method names from objects, instead of *strings* directly. It would allow for delegating the responsibility of handling those to the objects. In which case it would be:

```php
$compositionCollection->alias($methodObject, 'newMethodName', 'private');
// renders as: "MyTrait::myMethod as private newMethodName;"
// here would resolve the name of the trait and the method from their respective instances
```

What do you think? Are you going to continue with this on your branch?

**Comment by tonicospinelli** [comment]
KISS way!! :stuck_out_tongue_winking_eye: 

I will not delete my branch, if you want, add my repo into your remote and contribute with. If you have time to do, of course... if not, I can implement it until weekend :smile:

**Comment by tonicospinelli** [comment]
@jameswatts can you take a look on PR #5 and make a code review?

Next step, I think is good add factories for `alias`, `conflictingMethod` and `visibility`, at moment I just implement the feature to render it :wink:

**Comment by tonicospinelli** [comment]
@jameswatts with my last changes, get result like this:

```php
$compositionCollection->addMethod(new AliasMethod('MyTrait', 'myMethod', 'newMethodName', 'private'));
// renders as: "MyTrait::myMethod as private newMethodName;"
```

```php
$compositionCollection->addMethod(new VisibilityMethod('MyTrait', 'myMethod', 'protected');
// renders as: "MyTrait::myMethod as protected;"
```

```php
$compositionCollection->addMethod(new ConflictingMethod('MyTrait', 'myMethod', 'OtherTrait');
// renders as: "MyTrait::myMethod insteadof OtherTrait;"
```

**Comment by tonicospinelli** [comment]
@jameswatts if you want to see the final code, take a look at [PhpClassTest](https://github.com/tonicospinelli/ClassGeneration/pull/5/files#diff-bc959fa4ec8e046702517358c7a0fe7fR337)

**Comment by jameswatts** [comment]
Looks very good :+1: :clap:

I did notice though that the test was missing some cases, specifically aliasing, as well as both aliasing and setting visibility together in the class.

Also, there isn't the expectation that a trait be added to the class *before* aliasing or resolving conflicts, for example, from your test:

```php
->addComposition('A')
->addCompositionMethod(new Composition\VisibilityMethod('B', 'doSomething', Visibility::TYPE_PRIVATE))
->addCompositionMethod(new Composition\ConflictingMethod('C', 'toDo', 'B'));
```

Should there not be a call to `addComposition()` for "B" and "C" before any trait configurations are defined?

I'm personally not too concerned about it, as it's nice to be able to shortcut those calls, I'm just thinking about APIs which may build on this library. What do you think?

**Comment by tonicospinelli** [comment]
Thanks man!!

> Should there not be a call to addComposition() for "B" and "C" before any trait configurations are defined?

with current implementation, no! The `addCompositionMethod` method will try to add a composition based on trait name (case you did forget to add trait name with `addComposition`, like fall back) :wink: 

If you want to turn explicit, you can add the lines, no problem! 
```php
->addComposition('A')
->addComposition('B')
->addComposition('C')
->addCompositionMethod(new Composition\VisibilityMethod('B', 'doSomething', Visibility::TYPE_PRIVATE))
->addCompositionMethod(new Composition\ConflictingMethod('C', 'toDo', 'B'));
```

**Comment by jameswatts** [comment]
OK, then +1 from me 100% :+1: :smiley:

**Comment by tonicospinelli** [comment]
nice! I will bump new tag 2.2 after merge PR #5

**Comment by jameswatts** [comment]
I think we can close this issue now, right?

**Comment by tonicospinelli** [comment]
yeah!! closing!
